//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feedback_facul.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class glassDbEntities : DbContext
    {
        public glassDbEntities()
            : base("name=glassDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlunoMatriculado> tb_aluno_matriculado { get; set; }
        public virtual DbSet<Avaliacao> tb_avaliacao { get; set; }
        public virtual DbSet<Categoria> tb_categoria { get; set; }
        public virtual DbSet<Consistencia> tb_consistencia { get; set; }
        public virtual DbSet<Curso> tb_curso { get; set; }
        public virtual DbSet<Instituicao> tb_instituicao { get; set; }
        public virtual DbSet<Parger> tb_parger { get; set; }
        public virtual DbSet<Quesito> tb_quesito { get; set; }
        public virtual DbSet<Usuario> tb_usuario { get; set; }
    }
}
